version: '3.8'

services:
  db:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  cache:
    image: redis:7.2.4
    ports:
      - "6379:6379"

  web:
    build: ./app
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - cache
  
volumes:
  postgres_data: